import type { DatabaseState } from "./schema";
import { hashPassword } from "../security/password";
import { createDefaultStudentWorkflowState } from "./default-student-workflow-state";

const demoActivatedAt = "2026-06-06T00:00:00.000Z";

export const createDefaultDatabaseState = (): DatabaseState => ({
  schemaVersion: 7,
  users: [
    {
      id: "usr_mhs_01",
      role: "mahasiswa",
      name: "Dimas Indra Jaya",
      identifier: "mahasiswa",
      email: "mahasiswa@pharmsita.local",
      status: "Aktif",
      passwordHash: hashPassword("demo"),
      passwordStatus: "active",
      forceChangeOnLogin: false,
      lastLoginAt: null,
      firstLoginCompletedAt: demoActivatedAt,
      passwordChangedAt: demoActivatedAt,
    },
    {
      id: "usr_dosen_01",
      role: "dosen",
      name: "Dr. Budi Harto, M.Farm.",
      identifier: "dosen",
      email: "dosen@pharmsita.local",
      status: "Aktif",
      passwordHash: hashPassword("demo"),
      passwordStatus: "active",
      forceChangeOnLogin: false,
      lastLoginAt: null,
      firstLoginCompletedAt: demoActivatedAt,
      passwordChangedAt: demoActivatedAt,
    },
    {
      id: "usr_admin_01",
      role: "admin",
      name: "Admin PharmSITA",
      identifier: "admin",
      email: "admin@pharmsita.local",
      status: "Aktif",
      passwordHash: hashPassword("demo"),
      passwordStatus: "active",
      forceChangeOnLogin: false,
      lastLoginAt: null,
      firstLoginCompletedAt: demoActivatedAt,
      passwordChangedAt: demoActivatedAt,
    },
    {
      id: "usr_koor_01",
      role: "koordinator",
      name: "Koordinator TA",
      identifier: "kordinator",
      email: "koordinator@pharmsita.local",
      status: "Aktif",
      passwordHash: hashPassword("demo"),
      passwordStatus: "active",
      forceChangeOnLogin: false,
      lastLoginAt: null,
      firstLoginCompletedAt: demoActivatedAt,
      passwordChangedAt: demoActivatedAt,
    },
    {
      id: "usr_multi_01",
      role: "dosen",
      name: "Dr. Multi Peran, M.Farm.",
      identifier: "multi",
      email: "multi@pharmsita.local",
      status: "Aktif",
      passwordHash: hashPassword("demo"),
      passwordStatus: "active",
      forceChangeOnLogin: false,
      lastLoginAt: null,
      firstLoginCompletedAt: demoActivatedAt,
      passwordChangedAt: demoActivatedAt,
    },
    {
      id: "usr_first_01",
      role: "mahasiswa",
      name: "Mahasiswa Aktivasi Pertama",
      identifier: "firstlogin",
      email: "firstlogin@pharmsita.local",
      status: "Aktif",
      passwordHash: hashPassword("demo"),
      passwordStatus: "needs_activation",
      forceChangeOnLogin: true,
      lastLoginAt: null,
      firstLoginCompletedAt: null,
      passwordChangedAt: null,
    },
  ],
  userRoles: [
    {
      userId: "usr_mhs_01",
      role: "mahasiswa",
      status: "Aktif",
      createdAt: demoActivatedAt,
      createdBy: null,
    },
    {
      userId: "usr_dosen_01",
      role: "dosen",
      status: "Aktif",
      createdAt: demoActivatedAt,
      createdBy: null,
    },
    {
      userId: "usr_admin_01",
      role: "admin",
      status: "Aktif",
      createdAt: demoActivatedAt,
      createdBy: null,
    },
    {
      userId: "usr_koor_01",
      role: "koordinator",
      status: "Aktif",
      createdAt: demoActivatedAt,
      createdBy: null,
    },
    {
      userId: "usr_multi_01",
      role: "dosen",
      status: "Aktif",
      createdAt: demoActivatedAt,
      createdBy: null,
    },
    {
      userId: "usr_multi_01",
      role: "koordinator",
      status: "Aktif",
      createdAt: demoActivatedAt,
      createdBy: null,
    },
    {
      userId: "usr_first_01",
      role: "mahasiswa",
      status: "Aktif",
      createdAt: demoActivatedAt,
      createdBy: null,
    },
  ],
  finalProjectRegistrations: [],
  refreshTokens: [],
  auditLogs: [],
  permissionsByRole: {
    mahasiswa: [
      "student.workflow.read",
      "student.workflow.submit",
      "student.final-project-registration.read",
      "student.final-project-registration.submit",
    ],
    dosen: [
      "lecturer.workflow.read",
      "lecturer.guidance.read",
      "lecturer.guidance.approve",
      "lecturer.exam.assess",
      "lecturer.revision.review",
      "lecturer.final-project-registration.read",
    ],
    admin: [
      "admin.users.manage",
      "admin.master.manage",
      "audit.read",
      "workflow.override",
      "admin.final-project-registration.override",
    ],
    koordinator: [
      "coordinator.workflow.read",
      "coordinator.progress.manage",
      "coordinator.exam.manage",
      "coordinator.validation.manage",
      "coordinator.monitoring.read",
      "coordinator.final-project-registration.read",
      "coordinator.final-project-registration.validate",
    ],
  },
  masterData: {
    academicPeriods: [
      {
        id: "period_2025_2026_ganjil",
        name: "2025/2026",
        semester: "Ganjil",
        startDate: "2025-08-01",
        endDate: "2026-01-31",
        status: "Aktif",
      },
    ],
    thesisTypes: [
      {
        id: "thesis_type_01",
        name: "Skripsi Penelitian",
        skema: "Skripsi",
        desc: "Tugas akhir berbasis penelitian laboratorium atau lapangan.",
        status: "Aktif",
      },
      {
        id: "thesis_type_02",
        name: "Studi Literatur",
        skema: "Non Skripsi",
        desc: "Tugas akhir berbasis kajian literatur sistematis.",
        status: "Aktif",
      },
    ],
    supportingDocuments: [
      {
        id: "doc_01",
        name: "KHS Terakhir",
        description: "Dokumen KHS semester terakhir.",
        allowedTypes: ["PDF"],
        isRequired: "Wajib",
        status: "Aktif",
      },
    ],
    requirements: [
      {
        id: "req_01",
        tahap: "Persyaratan Awal",
        namaPersyaratan: "IPK minimal 3.00 dan SKS minimal 120",
        deskripsiAturan: "Divalidasi oleh koordinator.",
        wajib: true,
        status: "Aktif",
      },
    ],
  },
  studentWorkflows: {
    usr_mhs_01: createDefaultStudentWorkflowState(),
    "1": createDefaultStudentWorkflowState(),
  },
  studentWorkflow: createDefaultStudentWorkflowState(),
});
